services:
  - type: web
    name: youtube-stream-test
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    numInstances: 1
    region: oregon
    autoDeploy: true